@startuml
!include C4_Container.puml

title MonitorSystem Container Diagram

top to bottom direction

Person(director, "Директор", "Просматривает отчёты и общие показатели")
Person(analyst, "Аналитик", "Настраивает метрики и анализирует данные")
Person(operator, "Оператор", "Следит за системой мониторинга и реагирует на тревоги")

Container_Boundary(Sensors, "Датчики") {
  Container(FoodSensor, "Датчик кормушки", "Устройство", "Контролирует наличие корма")
  Container(WaterSensor, "Датчик поилки", "Устройство", "Контролирует наличие воды")
  Container(WaterFilterSensor, "Датчик фильтрации воды", "Устройство", "Следит за фильтрацией")
  Container(VideoSystem, "Система видеонаблюдения", "Камеры", "Наблюдает за животными")
  Container(MiniServer, "Шлюз IoT", "Устройство", "Сбор данных с датчиков и камер")
  Container(SensorTracker, "Сервис обработки данных датчиков", "Python, Fastapi", "Принимает данные от датчиков, публикует события и передаёт медиафайлы для анализа")
}

Container(kafka, "Брокер сообщений", "Apache Kafka", "Шина данных")
Container(HeadOfficeSystem, "Центральный сервер", "", "Головной офис. Собирает данные со всех ферм")


Container_Boundary(MonitorSystem, "Система мониторинга") {
  Container(MainApp, "Веб Приложение", "Python, Fastapi", "Мониторинг и аналитика показаний датчиков. Уведомление оператора")
  Container(Database, "Database", "PostgreSQL", "Хранит обработанные данные")
  Container(AuthService, "Сервис авторизации", "Python", "Система для авторизации и аутентификации пользователей, управления ролями")
}

System_Ext(api, "Third-Party API", "REST", "API для мобильных или веб-приложений")
System_Ext(AI_model, "Нейросетевая модель", "Анализирует состояние животных по фото и видео")

Rel(operator, MainApp, "")
Rel(director, MainApp, "")
Rel(analyst, MainApp, "")

Rel(FoodSensor,MiniServer, "Передает данные", "Zigbee")
Rel(WaterSensor,MiniServer,"Передает данные", "Zigbee")
Rel(WaterFilterSensor,MiniServer,"Передает данные", "Zigbee")
Rel(VideoSystem,MiniServer,"Передает данные", "RTSP")
Rel(MiniServer,SensorTracker,"Передает данные", "HTTP/REST")
Rel(SensorTracker,kafka, "Публикует обработанные данные")
Rel(SensorTracker,AI_model,"Передача медиа данных для анализа")

Rel(MainApp,kafka,"Данные о состоянии фермы")
Rel(MainApp, AuthService, "Аутентификация и авторизация пользователей (OAuth2/JWT)")
Rel(kafka,HeadOfficeSystem, "Синхронизация данных с головным офисом")
Rel(MainApp, Database, "Чтение/запись данных (SQL)")
Rel(MainApp, api, "Предоставление данных о ферме (REST API)")
@enduml